### ISSUE TITLE
multiple callable won't get arguments

### ISSUE THREAD

**Issue by basz** [sukima/ember-confirmed#2]
adding multiple 'chainables' callbacks work but arguments aren't passed again...

```
return confirmer = new Confirmer((resolver) => {
    }).onConfirmed((...someArgs) => {
       console.log('onConfirmed 1', ...someArgs);
    }).onConfirmed((...someArg) => {
       console.log('onConfirmed 2', ...someArgs);
    });
```

with

```
resolver.confirm('xx');
```

outputs

```
[Log] onConfirmed 1 – "xx" (plhw-client.js, line 5961)
[Log] onConfirmed 2 – undefined (plhw-client.js, line 5972)
```

**Comment by sukima** [comment]
Confirmed, this is a bug. Looking into it.

**Comment by sukima** [comment]
I've gone over the code and can confirm this is not a bug. What is happening is that the **return value** of the first callback becomes the value for the next callback.

This is the same API and expectations for Promises. It allows chains to mutate the value and massage it as needed. Since this addon is implemented using Promises and I designed the API to follow the same specs I made sure that mutation was still allowed.

I added [tests to illustrate this](https://github.com/sukima/confirmed/commit/edeaedabe03f00a6c59af04e40bcd90c132512c5) since at first I thought it was a bug.

[You're Missing the Point of Promises](https://blog.domenic.me/youre-missing-the-point-of-promises/) goes into details on this concept.

**Comment by sukima** [comment]
To fix this in your example you need to return the value for the next chain:

```js
return confirmer = new Confirmer((resolver) => {
    }).onConfirmed((result) => {
       console.log('onConfirmed 1', result);
       return result;
    }).onConfirmed((result) => {
       console.log('onConfirmed 2', result);
       return result;
    });
```

**Comment by basz** [comment]
I see! Thx for the explanation.

**Comment by basz** [comment]
any chance the ...rest operator would be supported instead of an payload (result)?

resolver.confirm(arg1, arg2, arg3)

```
.onConfirmed((...args) => {
       console.log('onConfirmed 1', ...args);
       return ...args;
    })

```

**Comment by sukima** [comment]
Staying true to the Promise API this is not possible. You could solve this in the same way you would if you were to resolve a promise with multiple values:

```js
new Confirmer(({confirm}) => {
  confirm([arg1, arg2, arg3]);
})

// result is an array, you can use the spread operator
.onConfirmed((result) => {
  console.log('onConfirmed 1', ...result);
  return result;
})

// You can use destructuring to pull each element as a variable
.onConfirmed(([arg1, arg2, arg3]) => {
   console.log('onConfirmed 2', arg1, arg2, arg3);
   return [arg1, arg2, arg3];
});
```

Like in a promise there is only ever **one** value. For cases of multiple values the single value becomes an array.

```js
new Promise((resolve) => {
  resolve([arg1, arg2, arg3]);
})

// result is an array, you can use the spread operator
.then((result) => {
  console.log('then 1', ...result);
  return result;
})
  
// You can use destructuring to pull each element as a variable
.then(([arg1, arg2, arg3]) => {
   console.log('then 2', arg1, arg2, arg3);
   return [arg1, arg2, arg3];
});
```

**Comment by sukima** [comment]
Here is an [SO answer](https://stackoverflow.com/a/28703648/227176) addressing this very use case.

**Comment by basz** [comment]
clear! no problem then. won't try to swim against the stream. thanks again for your detailed answer...
